/*
 * Simple Messaging Test Service
 *
 * Simple messaging service used for testing
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Message struct {
	Index int64 `json:"index,omitempty"`
	Message string `json:"message,omitempty"`
	Source string `json:"source,omitempty"`
}
